### ISSUE TITLE
Artwork is blurry, while game is clear

### ISSUE THREAD

**Issue by tschak909** [libretro/mame2014-libretro#60]
See pictures, I suspect retroarch isn't making a canvas that's big enough to initially handle the artwork, and is loading in the artwork at a much lower resolution, and then scaling upward. 

Pictures here:

https://i.imgur.com/qraJ0SU.jpg
https://i.imgur.com/d2762ut.jpg

**Comment by hizzlekizzle** [comment]
Yes, that's exactly what's happening. If this core has an "alternate renderer" core option, it will make the canvas 1600x1200 or so, which will still have some scaling artifacts as it fits to your screen, but it looks better than the default tiny canvas.

The tradeoff is that most shaders look bad with the alternate renderer due to the huge resolution.

**Comment by tschak909** [comment]
Ok, so... am guessing nobody wants to fix this? ;)

-Thom

**Comment by andres-asm** [comment]
There is no way to fix this and keep our shaders working properly

**Comment by hizzlekizzle** [comment]
The alternative would be to start supporting mame's artwork format, or at least something similar, whereby an image with the same name as the game gets loaded as an overlay with some default settings (since most of them use the exact same 2-3 line cfg anyway).

**Comment by r-type** [comment]
Since no solution we can close it
